/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fs_ndk5_NDKTest */

#ifndef _Included_com_fs_ndk5_NDKTest
#define _Included_com_fs_ndk5_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fs_ndk5_NDKTest
 * Method:    getStringName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fs_ndk5_NDKTest_getStringName
  (JNIEnv *, jclass);

/*
 * Class:     com_fs_ndk5_NDKTest
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fs_ndk5_NDKTest_getSum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
